In [1]:
import pandas as pd
import os
os.chdir("F:\PML\Datasets")
from sklearn.linear_model import LinearRegression, Ridge , Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, GridSearchCV, cross_val_score
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [2]:
housing = pd.read_csv(r"F:\PML\Cases\Concrete_Strength\Concrete_Data.csv")
housing.columns

Index(['Cement', 'Blast', 'Fly', 'Water', 'Superplasticizer', 'Coarse', 'Fine',
       'Age', 'Strength'],
      dtype='object')

In [3]:
X = housing.drop('Strength', axis=1)
y = housing['Strength']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                   random_state=23)

In [5]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.intercept_, lr.coef_

(-7.6664343522079506,
 array([ 0.11499772,  0.10140332,  0.08255115, -0.17600505,  0.27810608,
         0.01264227,  0.01537017,  0.11424624]))

In [6]:
y_pred_lr = lr.predict(X_test)
print(r2_score(y_test, y_pred_lr))

0.6312960386440598


In [7]:
ridge = Ridge()
ridge.fit(X_train, y_train)
#ridge.intercept_, ridge.coef_

Ridge()

In [8]:
y_pred_rg = ridge.predict(X_test)
print(r2_score(y_test, y_pred_rg))

0.6312959887187692


In [9]:
ridge = Ridge(alpha=0.01)
ridge.fit(X_train, y_train)
y_pred_rg = ridge.predict(X_test)
print(r2_score(y_test, y_pred_rg))

0.6312960381450502


### Grid search using Ridge

In [10]:
params = {'alpha': [0.001, 0.01, 0.1, 1, 2, 5]}
kfold = KFold(n_splits=5, shuffle=True, random_state=23)

In [11]:
scores = []
for p in params['alpha']:
    ridge = Ridge(alpha=p)
    results = cross_val_score(ridge, X, y, cv=kfold)
    scores.append(results.mean())

In [12]:
i_max = np.argmax(scores)
print("Best alpha:", params['alpha'][i_max])
print("Best score:", scores[i_max])

Best alpha: 5
Best score: 0.6003629473268252


In [13]:
gcv = GridSearchCV(ridge, cv=kfold, param_grid=params)
gcv.fit(X, y)
print(gcv.best_params_)
print(gcv.best_score_)

{'alpha': 5}
0.6003629473268252


### Grid search using Lasso

In [14]:
lasso = Lasso()
params = {'alpha': [0.001, 0.01, 0.1, 1, 2, 5]}
kfold = KFold(n_splits=5, shuffle=True, random_state=23)
gcv = GridSearchCV(lasso, cv=kfold, param_grid=params)
gcv.fit(X, y)
print(gcv.best_params_)
print(gcv.best_score_)



{'alpha': 0.1}
0.6003715679740543


In [15]:
lasso = Lasso()
params = {'alpha': [0.001, 1, 2, 5]}
kfold = KFold(n_splits=5, shuffle=True, random_state=23)
gcv_ls = GridSearchCV(lasso, cv=kfold, param_grid=params)
gcv_ls.fit(X, y)




GridSearchCV(cv=KFold(n_splits=5, random_state=23, shuffle=True),
             estimator=Lasso(), param_grid={'alpha': [0.001, 1, 2, 5]})

In [16]:
print(gcv.best_params_)
print(gcv.best_score_)
best_lasso = gcv_ls.best_estimator_
dict(zip(X.columns, best_lasso.coef_))


{'alpha': 0.1}
0.6003715679740543


{'Cement': 0.1198028435517716,
 'Blast': 0.10386387483710076,
 'Fly': 0.08793328786051845,
 'Water': -0.1499360925047414,
 'Superplasticizer': 0.29215717900174265,
 'Coarse': 0.018082427920204338,
 'Fine': 0.020187525533047635,
 'Age': 0.11422159725570433}

#### elastic

In [17]:
elastic = ElasticNet()
elastic.fit(X_train, y_train)
params = {'alpha': [0.001, 0.01, 1, 1.5, 2, 5, 10],
         'l1_ratio': [0, 0.25, 0.3, 0.75, 1 ]}
kfold = KFold(n_splits=5, shuffle=True, random_state=23)
params
gcv = GridSearchCV(elastic, cv=kfold, param_grid=params)
gcv.fit(X,y)
pd.DataFrame(gcv.cv_results_)
#gcv.cv_results_ gives o/p as dictionary.


C:\Users\dbda\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.522e+04, tolerance: 2.258e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\dbda\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.313e+04, tolerance: 2.326e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers im

C:\Users\dbda\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.547e+04, tolerance: 2.258e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\dbda\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.346e+04, tolerance: 2.326e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers im

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0        0.004792  1.159995e-03         0.001193    3.881715e-04       0.001   
1        0.002000  1.226260e-05         0.000998    1.840616e-06       0.001   
2        0.002395  4.879249e-04         0.000996    2.740881e-06       0.001   
3        0.001994  1.997031e-06         0.001199    3.994591e-04       0.001   
4        0.002198  3.972901e-04         0.001191    3.883368e-04       0.001   
5        0.004388  4.850147e-04         0.000997    1.633820e-06        0.01   
6        0.001995  2.381323e-06         0.001197    3.971818e-04        0.01   
7        0.001996  2.114277e-06         0.000996    2.631692e-06        0.01   
8        0.001996  1.360449e-06         0.000996    8.529922e-07        0.01   
9        0.001994  1.569758e-05         0.001196    3.997630e-04        0.01   
10       0.004589  8.010477e-04         0.000999    3.746739e-06           1   
11       0.001995  3.642736e-06         0.000997    4.759781e-06           1   
12       0.001797  3.977182e-04         0.000995    2.319410e-06           1   
13       0.001996  3.059199e-06         0.000996    3.343305e-06           1   
14       0.001598  4.848595e-04         0.000996    3.653332e-06           1   
15       0.004585  4.888528e-04         0.001199    3.979239e-04         1.5   
16       0.001996  2.757422e-06         0.000996    7.325311e-07         1.5   
17       0.001995  2.132481e-06         0.000996    2.153700e-06         1.5   
18       0.001802  4.019008e-04         0.000991    1.119339e-05         1.5   
19       0.001796  3.996623e-04         0.001196    3.993045e-04         1.5   
20       0.004588  4.887536e-04         0.000997    1.631034e-06           2   
21       0.001999  2.934002e-06         0.000995    2.003851e-06           2   
22       0.001597  4.853344e-04         0.001195    3.848140e-04           2   
23       0.001988  8.568486e-06         0.001402    4.965775e-04           2   
24       0.001988  1.089800e-05         0.001005    1.405368e-05           2   
25       0.004192  3.966513e-04         0.001193    3.866333e-04           5   
26       0.001598  4.866633e-04         0.001195    3.954652e-04           5   
27       0.001993  4.371845e-06         0.000999    4.506048e-06           5   
28       0.000999  1.482036e-06         0.001196    4.019044e-04           5   
29       0.001795  4.021020e-04         0.001196    3.978264e-04           5   
30       0.004783  3.992659e-04         0.001002    3.959759e-06          10   
31       0.001596  4.897312e-04         0.001195    3.996461e-04          10   
32       0.001995  6.106495e-07         0.000997    1.144409e-06          10   
33       0.001395  4.884439e-04         0.000998    1.662788e-06          10   
34       0.001191  3.986512e-04         0.001002    1.239630e-05          10   

   param_l1_ratio                              params  split0_test_score  \
0               0     {'alpha': 0.001, 'l1_ratio': 0}           0.668250   
1            0.25  {'alpha': 0.001, 'l1_ratio': 0.25}           0.668249   
2             0.3   {'alpha': 0.001, 'l1_ratio': 0.3}           0.668249   
3            0.75  {'alpha': 0.001, 'l1_ratio': 0.75}           0.668249   
4               1     {'alpha': 0.001, 'l1_ratio': 1}           0.668248   
5               0      {'alpha': 0.01, 'l1_ratio': 0}           0.668247   
6            0.25   {'alpha': 0.01, 'l1_ratio': 0.25}           0.668243   
7             0.3    {'alpha': 0.01, 'l1_ratio': 0.3}           0.668243   
8            0.75   {'alpha': 0.01, 'l1_ratio': 0.75}           0.668236   
9               1      {'alpha': 0.01, 'l1_ratio': 1}           0.668232   
10              0         {'alpha': 1, 'l1_ratio': 0}           0.667985   
11           0.25      {'alpha': 1, 'l1_ratio': 0.25}           0.667576   
12            0.3       {'alpha': 1, 'l1_ratio': 0.3}           0.667490   
13           0.75      {'alpha': 1, 'l1_ratio': 0.75}      

In [18]:
print(gcv.best_params_)
print(gcv.best_score_)

{'alpha': 5, 'l1_ratio': 0}
0.600643179394704


#### Best estimatior

In [19]:
best_el = gcv_ls.best_estimator_
dict(zip(X.columns, best_el.coef_))

{'Cement': 0.1198028435517716,
 'Blast': 0.10386387483710076,
 'Fly': 0.08793328786051845,
 'Water': -0.1499360925047414,
 'Superplasticizer': 0.29215717900174265,
 'Coarse': 0.018082427920204338,
 'Fine': 0.020187525533047635,
 'Age': 0.11422159725570433}

In [20]:
best_el.intercept_, best_el.coef_

(-23.321076605123253,
 array([ 0.11980284,  0.10386387,  0.08793329, -0.14993609,  0.29215718,
         0.01808243,  0.02018753,  0.1142216 ]))

In [21]:
test = pd.read_csv(r"F:\PML\Cases\Concrete_Strength\testConcrete.csv")
best_es = gcv_ls.best_estimator_
best_es.predict(test)

array([68.73746243, 31.79008383, 19.49411398, 46.85099828, 58.04230926,
       16.09500148, 50.35397155, 80.31070596, 31.13524312, 41.56861521,
       43.44398337, 60.77099675, 52.37229437, 15.38766485])